spring:
  application:
    name: diploma-project
  datasource:
    url: jdbc:mysql://localhost:3306/player_analyzer?createDatabaseIfNotExist=true
    username: vardan
    password: Vardan_2026!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      # Hibernate больше не меняет базу! Он только проверяет структуру.
      ddl-auto: validate
  liquibase:
    # Указываем путь к главному файлу миграций
    change-log: classpath:db/changelog/db.changelog-master.yaml

# Твои кастомные настройки
app:
  import:
    file:
      path: /home/vardan/Desktop/HelloJava/diploma-project/players.csv